language: node_js
sudo: false
node_js:
  - "7.8.0"
script:
  - docker pull postgres
  - docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 postgres
  - sleep 10
  - npm install -g typescript ts-node
  - npm install
  - npm start &
  - sleep 5
  - npm test
