language: node_js
sudo: false
node_js:
  - "7.8.0"
script:
  - docker pull postgres
  - docker ps
  - docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 5433:5432 postgres
  - sleep 10
  - npm install -g typescript ts-node nyc
  - npm install
  - export NODE_ENV=test && ts-node bootstrap/seeder.ts
  - export NODE_ENV=test && ts-node src/app.ts &
  - sleep 5
  - npm test
