"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.USER_BY_ID = "SELECT au.* \n  FROM app_user au \n  WHERE au.id = $1";
exports.USER_BY_USERNAME = "SELECT au.* \n  FROM app_user au \n  WHERE au.username = lower($1)";
exports.ROLES_BY_USER_ID = "SELECT r.role \n  FROM user_role ur \n  INNER JOIN role r ON ur.role_id = r.id \n  WHERE ur.user_id = $1";
exports.USERS_LIMIT = "SELECT au.*\n  FROM app_user au\n  ORDER BY au.id\n  LIMIT $1 OFFSET $2\n  ";
exports.INSERT_USER = "INSERT INTO app_user \n  (id, username, password, first_name, last_name)\n  VALUES\n  (DEFAULT, lower($1), $2, $3, $4) RETURNING id";
exports.ACTIVATE_USER_BY_ID = "UPDATE app_user\n  SET activated = true\n  WHERE id = $1";
exports.INSERT_USER_ROLE = "INSERT INTO user_role (user_id, role_id)\n  VALUES ($1, $2)";
exports.UPDATE_USER_BY_USERNAME = "UPDATE app_user\n  SET first_name = $2,\n  last_name = $3,\n  biography = $4,\n  profile_image_id = $5\n  WHERE username = lower($1)\n  RETURNING id";
exports.UPDATE_PROFILE_IMAGE_BY_USERNAME = "UPDATE app_user\n  SET profile_image_id = $1\n  WHERE username = lower($2)\n  RETURNING id";
